samtools view -@ 2 -b -h -N only_2x_valid_id_1_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_1_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_10_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_10_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_11_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_11_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_12_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_12_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_13_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_13_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_14_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_14_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_15_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_15_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_16_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_16_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_17_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_17_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_18_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_18_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_19_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_19_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_2_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_2_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_3_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_3_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_4_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_4_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_5_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_5_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_6_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_6_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_7_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_7_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_8_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_8_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_9_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_9_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_20_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_20_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_21_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_21_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_22_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_22_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_23_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_23_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_24_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_24_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_25_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_25_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_26_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_26_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_27_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_27_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_28_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_28_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_29_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_29_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_30_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_30_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_31_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_31_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_32_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_32_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_33_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_33_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_34_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_34_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_35_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_35_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_36_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_36_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_37_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_37_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_38_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_38_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_39_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_39_tmp.bam
samtools view -@ 2 -b -h -N only_2x_valid_id_40_tmp.txt scMicro-ATAC-2x_aligned_sort.bam > scMicro-ATAC-2x_aligned_ligation_40_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_1_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_1_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_10_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_10_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_11_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_11_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_12_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_12_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_13_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_13_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_14_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_14_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_15_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_15_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_16_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_16_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_17_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_17_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_18_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_18_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_19_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_19_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_2_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_2_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_3_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_3_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_4_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_4_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_5_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_5_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_6_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_6_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_7_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_7_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_8_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_8_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_9_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_9_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_20_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_20_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_21_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_21_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_22_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_22_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_23_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_23_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_24_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_24_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_25_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_25_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_26_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_26_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_27_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_27_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_28_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_28_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_29_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_29_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_30_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_30_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_31_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_31_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_32_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_32_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_33_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_33_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_34_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_34_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_35_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_35_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_36_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_36_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_37_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_37_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_38_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_38_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_39_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_39_tmp.bam
samtools view -@ 2 -b -h -N only_12x_valid_id_40_tmp.txt scMicro-ATAC-12x_aligned_sort.bam > scMicro-ATAC-12x_aligned_ligation_40_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_1_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_1_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_10_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_10_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_11_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_11_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_12_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_12_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_13_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_13_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_14_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_14_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_15_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_15_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_16_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_16_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_17_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_17_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_18_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_18_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_19_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_19_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_2_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_2_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_3_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_3_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_4_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_4_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_5_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_5_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_6_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_6_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_7_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_7_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_8_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_8_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_9_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_9_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_20_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_20_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_21_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_21_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_22_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_22_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_23_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_23_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_24_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_24_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_25_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_25_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_26_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_26_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_27_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_27_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_28_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_28_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_29_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_29_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_30_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_30_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_31_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_31_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_32_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_32_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_33_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_33_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_34_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_34_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_35_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_35_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_36_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_36_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_37_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_37_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_38_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_38_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_39_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_39_tmp.bam
samtools view -@ 2 -b -h -N only_valid_id_40_tmp.txt MCC-old-po_aligned_sort.bam > MCC-old-po_aligned_ligation_40_tmp.bam
