sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_1_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_1_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_11_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_11_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_12_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_12_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_13_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_13_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_14_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_14_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_15_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_15_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_16_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_16_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_17_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_17_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_18_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_18_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_19_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_19_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_10_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_10_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_2_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_2_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_3_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_3_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_4_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_4_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_5_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_5_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_6_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_6_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_7_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_7_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_8_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_8_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_9_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_9_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_20_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_20_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_21_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_21_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_22_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_22_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_23_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_23_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_24_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_24_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_25_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_25_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_26_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_26_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_27_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_27_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_28_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_28_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_29_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_29_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_30_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_30_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_31_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_31_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_32_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_32_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_33_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_33_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_34_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_34_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_35_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_35_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_36_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_36_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_37_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_37_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_38_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_38_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_39_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_39_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-2x_aligned_ligation_40_tmp.bam -o scMicro-ATAC-2x_aligned_ligation_40_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_1_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_1_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_11_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_11_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_12_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_12_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_13_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_13_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_14_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_14_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_15_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_15_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_16_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_16_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_17_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_17_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_18_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_18_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_19_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_19_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_10_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_10_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_2_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_2_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_3_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_3_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_4_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_4_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_5_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_5_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_6_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_6_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_7_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_7_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_8_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_8_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_9_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_9_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_20_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_20_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_21_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_21_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_22_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_22_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_23_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_23_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_24_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_24_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_25_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_25_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_26_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_26_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_27_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_27_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_28_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_28_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_29_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_29_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_30_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_30_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_31_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_31_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_32_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_32_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_33_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_33_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_34_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_34_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_35_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_35_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_36_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_36_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_37_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_37_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_38_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_38_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_39_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_39_sort_tmp.bam
sambamba sort -t 4 scMicro-ATAC-12x_aligned_ligation_40_tmp.bam -o scMicro-ATAC-12x_aligned_ligation_40_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_1_tmp.bam -o MCC-old-po_aligned_ligation_1_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_11_tmp.bam -o MCC-old-po_aligned_ligation_11_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_12_tmp.bam -o MCC-old-po_aligned_ligation_12_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_13_tmp.bam -o MCC-old-po_aligned_ligation_13_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_14_tmp.bam -o MCC-old-po_aligned_ligation_14_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_15_tmp.bam -o MCC-old-po_aligned_ligation_15_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_16_tmp.bam -o MCC-old-po_aligned_ligation_16_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_17_tmp.bam -o MCC-old-po_aligned_ligation_17_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_18_tmp.bam -o MCC-old-po_aligned_ligation_18_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_19_tmp.bam -o MCC-old-po_aligned_ligation_19_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_10_tmp.bam -o MCC-old-po_aligned_ligation_10_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_2_tmp.bam -o MCC-old-po_aligned_ligation_2_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_3_tmp.bam -o MCC-old-po_aligned_ligation_3_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_4_tmp.bam -o MCC-old-po_aligned_ligation_4_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_5_tmp.bam -o MCC-old-po_aligned_ligation_5_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_6_tmp.bam -o MCC-old-po_aligned_ligation_6_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_7_tmp.bam -o MCC-old-po_aligned_ligation_7_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_8_tmp.bam -o MCC-old-po_aligned_ligation_8_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_9_tmp.bam -o MCC-old-po_aligned_ligation_9_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_20_tmp.bam -o MCC-old-po_aligned_ligation_20_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_21_tmp.bam -o MCC-old-po_aligned_ligation_21_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_22_tmp.bam -o MCC-old-po_aligned_ligation_22_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_23_tmp.bam -o MCC-old-po_aligned_ligation_23_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_24_tmp.bam -o MCC-old-po_aligned_ligation_24_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_25_tmp.bam -o MCC-old-po_aligned_ligation_25_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_26_tmp.bam -o MCC-old-po_aligned_ligation_26_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_27_tmp.bam -o MCC-old-po_aligned_ligation_27_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_28_tmp.bam -o MCC-old-po_aligned_ligation_28_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_29_tmp.bam -o MCC-old-po_aligned_ligation_29_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_30_tmp.bam -o MCC-old-po_aligned_ligation_30_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_31_tmp.bam -o MCC-old-po_aligned_ligation_31_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_32_tmp.bam -o MCC-old-po_aligned_ligation_32_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_33_tmp.bam -o MCC-old-po_aligned_ligation_33_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_34_tmp.bam -o MCC-old-po_aligned_ligation_34_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_35_tmp.bam -o MCC-old-po_aligned_ligation_35_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_36_tmp.bam -o MCC-old-po_aligned_ligation_36_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_37_tmp.bam -o MCC-old-po_aligned_ligation_37_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_38_tmp.bam -o MCC-old-po_aligned_ligation_38_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_39_tmp.bam -o MCC-old-po_aligned_ligation_39_sort_tmp.bam
sambamba sort -t 4 MCC-old-po_aligned_ligation_40_tmp.bam -o MCC-old-po_aligned_ligation_40_sort_tmp.bam